name: "Build LaTeX Sources"

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      - name: "Build exercises"
        run: ./bin/compile_exercises.sh --clean
